package frc.robot.shooting.regressions;

import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;
import frc.lib.util.FieldLayout;
import frc.robot.RobotConstants;
import java.util.function.Supplier;

public class ShooterVelocityRegressions {
	public class FerryRegressionConstants {

		public static final InterpolatingDoubleTreeMap NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();
		public static final InterpolatingDoubleTreeMap NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();

		public static final InterpolatingDoubleTreeMap NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();
		public static final InterpolatingDoubleTreeMap NEUTRAL_FEEDER_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();

		static {
			NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MIN_VALUE, 1800.0);
			NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(4.977, 1800.0);
			NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(5.976, 1850.0);
			NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(6.902, 1900.0);
			NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(7.912, 2050.0);
			NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(8.477, 2100.0);
			NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.029, 2200.0);
			NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.590, 2400.0);
			NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(10.061, 2550.0);
			NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MAX_VALUE, 2650.0);
		}

		static {
			NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MIN_VALUE, 52.5);
			NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(4.977, 52.5);
			NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(5.976, 51.5);
			NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(6.902, 50.5);
			NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(7.912, 49.5);
			NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(8.477, 48.5);
			NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.029, 46.5);
			NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.590, 45.5);
			NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(10.061, 43.5);
			NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MAX_VALUE, 43.0);
		}

		static {
			NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MIN_VALUE, 1600.0);
			NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(4.977, 1650.0);
			NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(5.976, 1700.0);
			NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(6.902, 1750.0);
			NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(7.912, 1850.0);
			NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(8.477, 1900.0);
			NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.029, 2000.0);
			NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.590, 2200.0);
			NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(10.061, 2350.0);
			NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MAX_VALUE, 2400.0);
		}

		public static final ShootingRegressions NEUTRAL_REGRESSIONS = new ShootingRegressions(
				NEUTRAL_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP,
				NEUTRAL_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP,
				NEUTRAL_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP);

		public static final InterpolatingDoubleTreeMap ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();
		public static final InterpolatingDoubleTreeMap ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();

		public static final InterpolatingDoubleTreeMap ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();

		static {
			ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MIN_VALUE, 1800.0);
			ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(4.977, 1800.0);
			ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(5.976, 1850.0);
			ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(6.902, 1900.0);
			ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(7.912, 2050.0);
			ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(8.477, 2100.0);
			ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.029, 2200.0);
			ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.590, 2400.0);
			ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(10.061, 2550.0);
			ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MAX_VALUE, 2650.0);
		}

		static {
			ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MIN_VALUE, 52.5);
			ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(4.977, 52.5);
			ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(5.976, 51.5);
			ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(6.902, 50.5);
			ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(7.912, 49.5);
			ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(8.477, 48.5);
			ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.029, 46.5);
			ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.590, 45.5);
			ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(10.061, 43.5);
			ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MAX_VALUE, 43.0);
		}

		static {
			ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MIN_VALUE, 1600.0);
			ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(4.977, 1650.0);
			ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(5.976, 1700.0);
			ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(6.902, 1750.0);
			ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(7.912, 1850.0);
			ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(8.477, 1900.0);
			ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.029, 2000.0);
			ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(9.590, 2200.0);
			ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(10.061, 2350.0);
			ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MAX_VALUE, 2400.0);
		}

		public static final ShootingRegressions ALLIANCE_REGRESSIONS = new ShootingRegressions(
				ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP,
				ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP,
				ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP);

		public static final InterpolatingDoubleTreeMap FAR_ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();
		public static final InterpolatingDoubleTreeMap FAR_ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();

		public static final InterpolatingDoubleTreeMap FAR_ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();

		static {
			FAR_ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MIN_VALUE, 3100.0);
			FAR_ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(12.460, 3150.0);
			FAR_ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(13.133, 3500.0);
			FAR_ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MAX_VALUE, 3550.0);
		}

		static {
			FAR_ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MIN_VALUE, 45.0);
			FAR_ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(12.460, 45.0);
			FAR_ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(13.133, 45.0);
			FAR_ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MAX_VALUE, 45.0);
		}

		static {
			FAR_ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MIN_VALUE, 1400.0);
			FAR_ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(12.460, 1400.0);
			FAR_ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(13.133, 1300.0);
			FAR_ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MAX_VALUE, 1300.0);
		}

		public static final ShootingRegressions FAR_ALLIANCE_REGRESSIONS = new ShootingRegressions(
				FAR_ALLIANCE_HOOD_DISTANCE_VELOCITY_REGRESSION_MAP,
				FAR_ALLIANCE_SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP,
				FAR_ALLIANCE_TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP);
	}

	public class HubRegressionConstants {
		public static final Supplier<Translation2d> ktargetLocation =
				FieldLayout.getAllianceHubTranslation(RobotConstants.isRedAlliance);

		public static final InterpolatingDoubleTreeMap SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();
		public static final InterpolatingDoubleTreeMap HOOD_DISTANCE_ANGLE_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();

		public static final InterpolatingDoubleTreeMap TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP =
				new InterpolatingDoubleTreeMap();

		static {
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MIN_VALUE, 1815.0);
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(1.70, 1855.0);
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(2.000, 1875.0);
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(2.215, 1940.0);
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(2.495, 2015.0);
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(2.888, 2065.0);
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(3.222, 2130.0);
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(3.570, 2200.0);
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(3.830, 2240.0);
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(4.150, 2340.0);
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(4.750, 2365.0);
			SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MAX_VALUE, 2410.0);
		}

		static {
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(Double.MIN_VALUE, 17.5);
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(1.70, 17.5);
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(2.000, 18.5);
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(2.215, 19.0);
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(2.495, 19.5);
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(2.888, 20.5);
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(3.222, 21.5);
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(3.570, 22.5);
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(3.830, 23.0);
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(4.150, 24.5);
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(4.750, 26.5);
			HOOD_DISTANCE_ANGLE_REGRESSION_MAP.put(Double.MAX_VALUE, 27.0);
		}

		static {
			TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MIN_VALUE, 1400.0);
			TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(1.7, 1425.0);
			TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(2.215, 1450.0);
			TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(2.495, 1500.0);
			TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(2.888, 1550.0);
			TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(3.222, 1650.0);
			TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(3.570, 1750.0);
			TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(3.830, 1800.0);
			TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(4.150, 1950.0);
			TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(4.750, 2150.0);
			TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP.put(Double.MAX_VALUE, 2150.0);
		}

		public static final ShootingRegressions REGRESSIONS = new ShootingRegressions(
				HOOD_DISTANCE_ANGLE_REGRESSION_MAP,
				SHOOTER_DISTANCE_VELOCITY_REGRESSION_MAP,
				TUNNEL_DISTANCE_VELOCITY_REGRESSION_MAP);
	}
}
